variables:
  TAG_NAME: "arm64-dev"

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --platform=linux/arm64/v8 --pull -t "$CI_REGISTRY_IMAGE:${TAG_NAME}" .
    - docker push "$CI_REGISTRY_IMAGE:${TAG_NAME}"
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      exists:
        - Dockerfile
