variables:
  TAG_NAME: "arm64"
  REGISTRY_IMAGE_NAME: "$CI_REGISTRY/misafirperver/$CI_PROJECT_NAME:$TAG_NAME"

docker-build:
  image: docker:20
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker context create builder-context
    - docker buildx create --name builderx --driver docker-container --use builder-context
    - docker buildx build --tag "$REGISTRY_IMAGE_NAME" --push --platform=linux/arm64/v8 .
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - Dockerfile
